### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anti-matt-er** [anti-matt-er/psn-parser#1]
- [ ] Create a README
- [ ] Test card validation
- [ ] Allow win information to be omitted
- [ ] Validate explicit notation against parser assumptions (for example, if it is written that BTN wins pot, this must be consistent with the assumed winner when parsing all information in the hand)
- [ ] Validate actions; must be legal
- [ ] Create method for outputting all parsed info
